---
- hosts: "{{ hosts }}"
  tasks:
    - shell: 'if [ ! -d /root/scripts ]; then { mkdir /root/scripts; }; fi '
    - shell: 'if [ ! -d /root/scripts/ipt ]; then { mkdir /root/scripts/ipt; }; fi '

- hosts: "{{ hosts }}"
  tasks:
  - name: install the latest version of ipset
    yum: name=ipset state=installed
    when: ansible_os_family  == "RedHat"

- hosts: "{{ hosts }}"
  tasks:
  - name: install the latest version of ipset
    apt: name=ipset state=installed
    when: ansible_os_family  == "Debian"

- hosts: "{{ hosts }}"
  tasks:
    - shell: 'sleep 10'

- hosts: "{{ hosts }}"
  roles: 
    - ipt2
